export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const RESET_STATE = 'RESET_STATE'
export const LOADING_ACC = 'LOADING_ACC'
export const LOADED_ACC = 'LOADED_ACC'
export const IMG_URL = 'IMG_URL'
export const ERROR = 'ERROR'
export const ERROR_IMG = 'ERROR'
export const RESET_ERROR = 'RESET_ERROR'
export const RESET_ERROR_IMG = 'RESET_ERROR'
export const ALERT_UPDATE = 'ALERT_UPDATE'
export const ALERT_AVATAR = 'ALERT_AVATAR'
export const ALERT_LOGOUT = 'ALERT_LOGOUT'
export const RESET_ALERT = 'RESET_ALERT'

